### ISSUE TITLE
How could I make all visible moons show in the terminal?

### ISSUE THREAD

**Issue by BULL3TB0T** [YoBii/LethalMoonUnlocks#1]
I'm not sure if this is a problem but could you tell me where is that setting in the config file? I think I already configured everything right but some moons still not show up that are supposed to be visible. What am I doing wrong here?

[LethalMoonUnlocks.zip](https://github.com/user-attachments/files/16912559/LethalMoonUnlocks.zip)

**Comment by YoBii** [comment]
So you have Discovery Mode set to `false` which means no moons are hidden by me.
Are the moons that are not showing hidden by LLL maybe? Or are you also using LethalConstellations?

**Comment by BULL3TB0T** [comment]
I don't have LethalConstellations mod installed.

**Comment by YoBii** [comment]
You're config seems correct. Did you try a new save? 

Send me your `Player.log` or share me your profile code and I can probably figure out what's wrong.

**Comment by BULL3TB0T** [comment]
I just checked with/without ur mod, and yes. it's missing moons because of your mod.

**Comment by YoBii** [comment]
Hmm, that's really odd. I never write to the hidden flag of a level if Discovery Mode is disabled and LethalConstellations is not installed.  
I just double checked to make sure.

Do you ever see a line like this in debug logs?
```
[Debug  :LethalMoonUnlocks] Icebound is visible in terminal moon catalogue
```

**Comment by YoBii** [comment]
Are the moons that are missing custom moons or vanilla moons? Do they have anything in common like being from the same pack or something. Grasping at straws here but hey.

**Comment by BULL3TB0T** [comment]
[Info   :LethalMoonUnlocks] Checking for compatible mods..
[Info   :LethalMoonUnlocks] Refreshing config..
[Info   :LethalMoonUnlocks] Discount rates (% off): 50%, 75%, 100%
[Info   :LethalMoonUnlocks] No custom moon group defined. Skip parsing..
[Info   :LethalMoonUnlocks] Register Network messages..
[Info   :LethalMoonUnlocks] NetworkManager created.

This is the startup.

[Info   :LethalMoonUnlocks] Terminal is booting up!
[Info   :LethalMoonUnlocks] Refreshing config..
[Info   :LethalMoonUnlocks] Discount rates (% off): 50%, 75%, 100%
[Info   :LethalMoonUnlocks] No custom moon group defined. Skip parsing..
[Info   :LethalMoonUnlocks] Initializing LMUnlockables from Extended levels..
[Info   :LethalMoonUnlocks] Loading save data..
[Info   :LethalMoonUnlocks] No save data found! New save..
[Info   :LethalMoonUnlocks] Syncing unlockables to all clients..

This is when I joined the game

**Comment by BULL3TB0T** [comment]
> Are the moons that are missing custom moons or vanilla moons? Do they have anything in common like being from the same pack or something. Grasping at straws here but hey.

I have bunch of custom moons, I can send a list of it from the log right here.

[Info   :LethalLevelLoader] LethalLevelLoader Loaded The Following ExtendedLevels:
1. 41 Experimentation (Vanilla)
2. 220 Assurance (Vanilla)
3. 56 Vow (Vanilla)
4. 71 Gordion (Vanilla)
5. 61 March (Vanilla)
6. 20 Adamance (Vanilla)
7. 85 Rend (Vanilla)
8. 7 Dine (Vanilla)
9. 21 Offense (Vanilla)
10. 8 Titan (Vanilla)
11. 68 Artifice (Vanilla)
12. 44 Liquidation (Vanilla)
13. 5 Embrion (Vanilla)
14. 10 EGypt (Custom)
15. 57 Asteroid-13 (Custom)
16. 44 Atlantica (Custom)
17. 64 Castle Grounds (Custom)
18. 42 Cosmocos (Custom)
19. 38 Crest (Custom)
20. 48 Desolation (Custom)
21. 16 Dust2 (Custom)
22. 154 Etern (Custom)
23. 25 Fission-C (Custom)
24. 2742 Jabiua (Custom)
25. 597 Siabudabu (Custom)
26. 36 Gloom (Custom)
27. 147 Gratar (Custom)
28. 46 Infernis (Custom)
29. 84 Junic (Custom)
30. 160 Taiga (Custom)
31. 134 Oldred (Custom)
32. Outpost 31 (Custom)
33. 94 Polarus (Custom)
34. 76 Acidir (Custom)
35. 15-MAOY School (Custom)
36. 112 Aquatis (Custom)
37. 43 Orion (Custom)
38. 42 Auralis (Custom)
39. 74 Solace (Custom)
40. StarlancerZero (Custom)
41. 27 Triskelion (Custom)
42. 69 Toilation (Custom)
43. 32 Argent (Custom)
44. 39 Azure (Custom)
45. 618 Budapest (Custom)
46. 35 CaltPrime (Custom)
47. 9 Celestria (Custom)
48. Crystallum (Custom)
49. 30 Echelon (Custom)
50. 33 EchoReach (Custom)
51. 93 Harloth (Custom)
52. 13 Kast (Custom)
53. 153 Maritopia (Custom)
54. Nimbus (Custom)
55. 34 Nyx (Custom)
56. 111 PsychSanctum (Custom)
57. Sanguine (Custom)
58. Spectralis (Custom)
59. 37 Zenit (Custom)
60. 42 Tranquillity (Custom)
61. Atlas Abyss (Custom)
62. Secret Labs (Custom)

**Comment by YoBii** [comment]
Hmm, that's all looking very normal. 

If you check your `Player.log` which is located in `%APPDATA%\..\LocalLow\ZeekerssRBLX\Lethal Company\` you can see the list of moons that LMU is getting from LLL and handles from that point on but I expect it to match the list you've posted.
It might provide some insight via the `Ignored` column. 
```
[Info   :LethalMoonUnlocks] Initializing LMUnlockables from Extended levels..
[Debug  :LethalMoonUnlocks] | LMUnlockable         |  Bought |  Visits |   Free |  Discovered |    New |   Once |  Permanent |  OnSale |  Rate |  OGPrice |  Ignored |
[Debug  :LethalMoonUnlocks] | Experimentation      |       0 |       0 |      0 |       False |  False |  False |      False |   False |     0 |        0 |          |
[Debug  :LethalMoonUnlocks] | Assurance            |       0 |       0 |      0 |       False |  False |  False |      False |   False |     0 |       50 |          |
```

You can post the entire file here. 

It could of course be an incompatibility with another mod that I'm not aware of. Can you post your dependency string from mod manager or if you're installing manual a listing of your `plugins` directory?

**Comment by BULL3TB0T** [comment]
[Player.log](https://github.com/user-attachments/files/16918822/Player.log)

**Comment by BULL3TB0T** [comment]
> Hmm, that's all looking very normal.
> 
> If you check your `Player.log` which is located in `%APPDATA%\..\LocalLow\ZeekerssRBLX\Lethal Company\` you can see the list of moons that LMU is getting from LLL and handles from that point on but I expect it to match the list you've posted. It might provide some insight via the `Ignored` column.
> 
> ```
> [Info   :LethalMoonUnlocks] Initializing LMUnlockables from Extended levels..
> [Debug  :LethalMoonUnlocks] | LMUnlockable         |  Bought |  Visits |   Free |  Discovered |    New |   Once |  Permanent |  OnSale |  Rate |  OGPrice |  Ignored |
> [Debug  :LethalMoonUnlocks] | Experimentation      |       0 |       0 |      0 |       False |  False |  False |      False |   False |     0 |        0 |    false |
> [Debug  :LethalMoonUnlocks] | Assurance            |       0 |       0 |      0 |       False |  False |  False |      False |   False |     0 |       50 |    false |
> ```
> 
> You can post the entire file here.
> 
> It could of course be an incompatibility with another mod that I'm not aware of. Can you post your dependency string from mod manager or if you're installing manual a listing of your `plugins` directory?

I'm manually adding them.

**Comment by BULL3TB0T** [comment]
[Player.log](https://github.com/user-attachments/files/16918826/Player.log)
Here is the log.

**Comment by BULL3TB0T** [comment]
And I don't think there is any incompatibilty since this is the only mod that modifies the moons terminal list.

**Comment by YoBii** [comment]
Log looks good. Can't see any issues there.

**Comment by YoBii** [comment]
The moons catalogue is still generated by LethalLevelLoader.

When it goes through each moon it fires a public event. I listen on that event and respond with a modified preview string for that moon, which is everything shown in the terminal but the moon's name. LLL takes my response and appends it to the moon name.

So as long as there are no errors when opening the moons list it should be fine. 

I'm wondering if there might be a limit of total lines that can be displayed..? Is it like all moons from the bottom of the list that are missing?

I have over 100 custom moons and I haven't noticed something like that. But I also don't play without Discovery mode. Let me check that.

**Comment by BULL3TB0T** [comment]
Should I send screenshots?

**Comment by YoBii** [comment]
Sure, go ahead.

**Comment by BULL3TB0T** [comment]
![image](https://github.com/user-attachments/assets/44a0c1bb-9234-4489-b8f2-4b7750b47689)
![image](https://github.com/user-attachments/assets/a7334f73-5f94-4019-b338-f1c322767efd)
![image](https://github.com/user-attachments/assets/07794f15-9680-4aa9-a5f0-3773df04d07d)

**Comment by BULL3TB0T** [comment]
![image](https://github.com/user-attachments/assets/04af2bd6-d8fb-4b59-b187-72329c595e70)

**Comment by BULL3TB0T** [comment]
Tranquality is missing in this example. Without this mod, it shows every moon.

**Comment by YoBii** [comment]
Can you still type and route to it? 

Also please try disabling the terminal tags in config and see if that changes anything.

**Comment by BULL3TB0T** [comment]
Yea, I can still route to it but won't show in the list. I'll try disabling terminal tags.

**Comment by BULL3TB0T** [comment]
Wait a second. I think I know the problem.

**Comment by YoBii** [comment]
Oh, another thing. Do you think it's possible that scrolling the list once is scrolling too much and skipping entries?

**Comment by BULL3TB0T** [comment]
Can you configure scrolling?

**Comment by BULL3TB0T** [comment]
Lol. That's what I thought about right now.

**Comment by YoBii** [comment]
😁

Probably, yeah. Have to check.

**Comment by BULL3TB0T** [comment]
Yeah please check if you configure scrolling, if not. Then you could add that setting in the config file. Oh yeah by the way, I made that Permanent Moons mod. Thank you for mentioning it.

**Comment by YoBii** [comment]
I noticed. Sure thing. Pretty much been using it since day one :)

So I found this patch here by pacoito but I'm not sure if it's working currently. 
https://github.com/pacoito123/LC_StoreRotationConfig/blob/main/StoreRotationConfig/Patches/TerminalScrollMousePatch.cs

It appears to be straightforward but I haven't done anything with transpilers yet so I'm not sure what's wrong.

**Comment by BULL3TB0T** [comment]
You could add it to your mod to be able to change the scroll value. Would make it so much easier.

**Comment by YoBii** [comment]
Resolved https://github.com/YoBii/LethalMoonUnlocks/commit/873189b4bcf52450aab164f7e37d6bdb3c8bbe5e

Have some other stuff to do before release. Update will come tomorrow probably.

**Comment by BULL3TB0T** [comment]
Perfect! Thank you for helping. I'm closing this now.
